name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 * * 0"

jobs:
  html_documentation_link_checks:
    timeout-minutes: 5
    if: github.repository_owner == 'opensimhub'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 5
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - name: Install python packages
        run: pip install --user futures
      - name: Check links
        timeout-minutes: 3
        run: python ./.CI/check_html.py checkLinks ./OpenHPL/
